function getElementsByClassName(e,t){if(e.getElementsByClassName){return e.getElementsByClassName(t)}else{return function(t,n){if(n==null)n=document;var r=[],i=n.getElementsByTagName("*"),s=i.length,o=new RegExp("(^|\\s)"+t+"(\\s|$)"),u,a;for(u=0,a=0;u<s;u++){if(o.test(i[u].className)){r[a]=i[u];a++}}return r}(t,e)}}function bind_event(e,t,n){if(e.addEventListener){e.addEventListener(t,n,false);return true}else if(e.attachEvent){return e.attachEvent("on"+t,n)}else{t="on"+t;if(typeof e[t]==="function"){n=function(e,t){return function(){e.apply(this,arguments);t.apply(this,arguments)}}(e[t],n)}e[t]=n;return true}return false}function cancelDefaultAction(e){var t=e?e:window.event;if(t.preventDefault)t.preventDefault();t.returnValue=false;return false}Element.prototype.remove=function(){this.parentElement.removeChild(this)};NodeList.prototype.remove=HTMLCollection.prototype.remove=function(){for(var e=0,t=this.length;e<t;e++){if(this[e]&&this[e].parentElement){this[e].parentElement.removeChild(this[e])}}}

var open_eshop = open_eshop || {};
// Set width of modal 
open_eshop.width = 480;
// Set height of modal
open_eshop.height = 600;
// Set name of class to trigger model
open_eshop.click_class = 'oe_button';
// Set the css styles here... It would be appended to head
open_eshop.css = '.oe_button{} .open-eshop_noscroll{overflow: hidden;}';

open_eshop.over=open_eshop.ifrm={};open_eshop.init=function(e){t=document.createElement("style");t.type="text/css";if(t.styleSheet){t.styleSheet.cssText=e.css}else{t.appendChild(document.createTextNode(e.css))}document.getElementsByTagName("head")[0].appendChild(t);bind_event(document,"click",function(e){clkd=e.target||e.srcElement||window.event.target||window.event.srcElement;idd=clkd.getAttribute("id");if(typeof idd!="undefined"&&idd!=null){var t=getElementsByClassName(document,"open_eshop_iframe");while(t[0]){t[0].parentNode.removeChild(t[0])}document.body.className=document.body.className.replace(/\bopen-eshop_noscroll\b/,"");if(document.getElementById("open_eshop_iframe_mask"))document.getElementById("open_eshop_iframe_mask").remove()}});e._eles=getElementsByClassName(document,e.click_class);for(i=0;i<e._eles.length;i++){bind_event(e._eles[i],"click",function(t){bod=document.body;bod.className+=" open-eshop_noscroll";tar=t.target||t.srcElement||window.event.target||window.event.srcElement;over=document.createElement("DIV");over.style.position="fixed";over.style.display="inline";over.setAttribute("id","open_eshop_iframe_mask");over.style.top=0;over.style.left=0;over.style.margin=0;over.style.padding=0;over.style.zIndex=0xaae4fa579e6c5800;over.style.width="100%";over.style.height="100%";over.style.background="#000";over.style.opacity=.5;over.style.filter="alpha(opacity=50)";e.over[i]=over;bod.appendChild(over);ifrmc=document.createElement("DIV");ifrmc.setAttribute("id","open_eshop_iframe"+i);ifrmc.setAttribute("class","open_eshop_iframe");ifrmc.style.width=e.width+"px";ifrmc.style.height=e.height+"px";ifrmc.style.position="fixed";ifrmc.style.top="50%";ifrmc.style.left="50%";ifrmc.style.zIndex=9231424253536477e4;ifrmc.style.marginLeft="-"+e.width/2+"px";ifrmc.style.marginTop="-"+e.height/2+"px";ifrm=document.createElement("IFRAME");ifrm.setAttribute("src",tar.getAttribute("href"));ifrm.style.width=e.width+"px";ifrm.style.height=e.height+"px";ifrm.style.backgroundColor="transparent";ifrm.style.border=0;e.ifrm[i]=ifrmc;ifrmc.appendChild(ifrm);bod.appendChild(ifrmc);cancelDefaultAction(t)})}};window.onload=function(){open_eshop.init(open_eshop)}