<?php defined('SYSPATH') or die('No direct access allowed.');
/**
 * custom options for the theme
 * @var array
 */
return array(   
                'admin_theme' => array(     'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Change the admin color theme'),
                                            'options'   => array(   'bootstrap' => 'Original',
                                                                    'cerulean'  => 'Dark Blue',
                                                                    'cosmo'     => 'Metro Style',
                                                                    'spacelab'  => 'Spacelab',
                                                                    'united'    => 'Purple / Orange',
                                                                ), 
                                            'default'   => 'bootstrap',
                                            'required'  => TRUE),

                'fixed_toolbar' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Header tool bar gets fixed in the top'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ), 
                                            'default'   => '1',
                                            'required'  => TRUE),

                'breadcrumb' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Display breadcrumb'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ), 
                                            'default'   => '1',
                                            'required'  => TRUE),

                'logo_url' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('URL to your Logo. Recommended size 250px x 40px. Leave blank for none.'),
                                            'default'   => '',),
                'short_description' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('Short description that appears after the site name.'),
                                            'default'   => ''),

                'num_home_latest_ads' => array(   'type'      => 'text',
                                            'display'   => 'text',
                                            'label'     => __('Numbers of ads to display in home slider'),
                                            'default'   => 21,
                                            'required'  => TRUE),

                'sidebar_position' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Where you want the sidebar to appear'),
                                            'options'   => array(   'right' => __('Right side'),
                                                                    'left'  => __('Left side'),
                                                                ), 
                                            'default'   => 'right',
                                            'required'  => TRUE),

                'listing_slider' => array(   'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Display slider in listing'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ), 
                                            'default'   => '0',
                                            'required'  => TRUE),

                'header_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Header banner, allows HTML'),
                                            'default'   => '',),
                'footer_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Footer banner, allows HTML'),
                                            'default'   => '',),
                'listing_ad' => array(       'type'      => 'text',
                                            'display'   => 'textarea',
                                            'label'     => __('Listing random position banner, allows HTML'),
                                            'default'   => '',),
                'rtl' => array(             'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Content shift right to left'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ), 
                                            'default'   => '0',
                                            'required'  => TRUE),
                'cdn_files' => array(       'type'      => 'text',
                                            'display'   => 'select',
                                            'label'     => __('Uses CDN for CSS/JS'),
                                            'options'   => array(   '1' => __('Yes'),
                                                                    '0'  => __('No'),
                                                                ), 
                                            'default'   => '0',
                                            'required'  => TRUE),

);